tools:
    tests:
        override:
            -
                command: 'vendor/bin/codecept --coverage=coverage-clover'
                coverage:
                    file: 'tests/_output/coverage-clover'
                    format: 'clover'